---
- name: "PLAY 1: INTERFACE GET"
  hosts: "restconf_routers"
  tasks:
    # Issue HTTP GET for IETF interfaces and store result in rc_get
    - name: "TASK 1: Get IETF YANG interfaces config via RESTCONF"
      restconf_get:
        path: "/data/ietf-interfaces:interfaces"
      register: "rc_get"

    # Should exist, but create data_ref directory if it doesn't
    - name: "TASK 2: Ensure data_ref/ folder exists"
      file:
        path: "data_ref"
        state: "directory"
      run_once: true
      delegate_to: "localhost"

    # Write rc_get to disk in pretty JSON format on a per-host basis
    - name: "TASK 3: Write JSON to disk"
      copy:
        content: "{{ rc_get.response | to_nice_json(indent=2) }}"
        dest: "data_ref/{{ inventory_hostname }}_restconf_intfs.json"
...
