---
all:
  children:
    restconf_routers:
      hosts:
        latest:
          ansible_host: "ios-xe-mgmt-latest.cisco.com"  # IOS-XE 16.11.01a
        stable:
          ansible_host: "ios-xe-mgmt.cisco.com"  # IOS-XE 16.9.3

    netconf_routers:
      hosts:  # empty, but illustrates multiple groups
      vars:
        ansible_connection: "netconf"
...
