---
all:
  children:
    restconf_switches:
      hosts:
        cat9300:
          ansible_host: "10.10.20.100"  # IOS-XE 16.12.01ah1

    netconf_switches:
      hosts:  # empty, but illustrates multiple groups
      vars:
        ansible_connection: "netconf"
...
