---
# Connectivity parameters
ansible_connection: "httpapi"
ansible_network_os: "restconf"
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
ansible_httpapi_port: 9443
ansible_httpapi_restconf_root: "/restconf"  # default
ansible_user: "developer"
ansible_password: "C1sco12345"

# Infrastructure parameters
new_interfaces:
  interface:
    - name: "Loopback42518"
      description: "Anycast service address"
      type: "iana-if-type:softwareLoopback"
      enabled: true
      ietf-ip:ipv4:
        address:
          - ip: "192.0.2.42"
            netmask: "255.255.255.255"
...
